const questionData = [
    {
        id: "2025-01",
        year: "2025",
        unit: "Dynamics",
        topic: "Kinematics",
        question_text: "A car accelerates uniformly from rest and travels a distance of 18 m in 3.0 seconds. The speed of the car at 3.0 seconds is",
        question_image: "",
        table_headers: "",
        option_a: "4.0 m/s",
        option_b: "6.0 m/s",
        option_c: "12 m/s",
        option_d: "36 m/s",
        option_e: "54 m/s",
        correct_answer: "C"
    },
    {
        id: "2025-02",
        year: "2025",
        unit: "Dynamics",
        topic: "Kinematics",
        question_text: "A ball is thrown vertically upwards and then falls back to its starting position. Which of the following acceleration-time graphs represents the motion of the ball?",
        question_image: "",
        table_headers: "",
        option_a: "[IMG]2025_Q02_A.png",
        option_b: "[IMG]2025_Q02_B.png",
        option_c: "[IMG]2025_Q02_C.png",
        option_d: "[IMG]2025_Q02_D.png",
        option_e: "[IMG]2025_Q02_E.png",
        correct_answer: "A"
    },
    {
        id: "2025-03",
        year: "2025",
        unit: "Dynamics",
        topic: "Forces",
        question_text: "A force of 10.0 N pulls a trolley of mass 2.0 kg along a horizontal surface. The total frictional force acting on the trolley is 6.0 N. The acceleration of the trolley is",
        question_image: "2025_Q03_Diagram.png",
        table_headers: "",
        option_a: "2.0 m/s²",
        option_b: "3.0 m/s²",
        option_c: "5.0 m/s²",
        option_d: "8.0 m/s²",
        option_e: "10.0 m/s²",
        correct_answer: "A"
    },
    {
        id: "2025-04",
        year: "2025",
        unit: "Dynamics",
        topic: "Forces",
        question_text: "A block of wood of mass 3.5 kg slides down a slope. The block of wood has a constant acceleration of 2.3 m/s² down the slope. The force of friction acting on the block is 6.4 N. The angle of the slope is",
        question_image: "2025_Q04_Diagram.png",
        table_headers: "",
        option_a: "2.8°",
        option_b: "11°",
        option_c: "14°",
        option_d: "25°",
        option_e: "65°",
        correct_answer: "D"
    },
    {
        id: "2025-05",
        year: "2025",
        unit: "Dynamics",
        topic: "Energy",
        question_text: "An object is released from rest at a height of 1.6 m above the ground. The mass of the object is 0.20 kg. The maximum speed of the object just before it hits the ground is",
        question_image: "",
        table_headers: "",
        option_a: "4.0 m/s",
        option_b: "5.6 m/s",
        option_c: "13 m/s",
        option_d: "16 m/s",
        option_e: "31 m/s",
        correct_answer: "B"
    },
    {
        id: "2025-06",
        year: "2025",
        unit: "Dynamics",
        topic: "Impulse",
        question_text: "A ball of mass 0.164 kg is dropped from rest and falls towards the ground. The ball collides with the ground and rebounds upwards. The speed of the ball just before it hits the ground is 4.85 m/s. The ball is in contact with the ground for 0.180 s. The speed of the ball immediately after it rebounds from the ground is 3.96 m/s. The mean force exerted by the ball on the ground during the collision is",
        question_image: "",
        table_headers: "",
        option_a: "0.146 N",
        option_b: "0.811 N",
        option_c: "0.645 N",
        option_d: "1.44 N",
        option_e: "8.03 N",
        correct_answer: "E"
    },
    {
        id: "2025-07",
        year: "2025",
        unit: "Dynamics",
        topic: "Forces",
        question_text: "Two samples of modelling clay, X and Y, have the same shape and mass. Sample X is made of a softer clay than sample Y. The samples are both released from the same height and fall towards the ground. Both samples come to rest when they collide with the ground. A student makes the following statements about the samples colliding with the ground.<br><br>I Sample X comes to rest in less time than sample Y.<br>II The mean force exerted by the ground on sample X is less than the mean force exerted by the ground on sample Y.<br>III The change in momentum of sample X is less than the change in momentum of sample Y.<br><br>Which of these statements is/are correct?",
        question_image: "",
        table_headers: "",
        option_a: "I only",
        option_b: "II only",
        option_c: "I and II only",
        option_d: "I and III only",
        option_e: "II and III only",
        correct_answer: "B"
    },
    {
        id: "2025-08",
        year: "2025",
        unit: "Relativity",
        topic: "Time Dilation",
        question_text: "The Large Hadron Collider (LHC) is contained in a circular tunnel. A technician working at the LHC measures the length of the tunnel to be 26.7 km. Protons in the tunnel are accelerated to a speed of 0.999c. The length of the tunnel in the frame of reference of the protons is",
        question_image: "",
        table_headers: "",
        option_a: "0.844 km",
        option_b: "1.19 km",
        option_c: "26.7 km",
        option_d: "597 km",
        option_e: "844 km",
        correct_answer: "B"
    },
    {
        id: "2025-09",
        year: "2025",
        unit: "Space",
        topic: "Cosmology",
        question_text: "A student makes the following statements about cosmic microwave background radiation.<br><br>I Cosmic microwave background radiation provides evidence for the Big Bang theory.<br>II Cosmic microwave background radiation reaches the Earth from all directions.<br>III Measurements of the peak wavelength of cosmic microwave background radiation indicate that the average temperature of the Universe was lower in the past than it is now.<br><br>Which of these statements is/are correct?",
        question_image: "",
        table_headers: "",
        option_a: "I only",
        option_b: "II only",
        option_c: "I and II only",
        option_d: "II and III only",
        option_e: "I, II and III",
        correct_answer: "C"
    },
    {
        id: "2025-10",
        year: "2025",
        unit: "Electricity",
        topic: "Fields",
        question_text: "A potential difference of 1.2 kV is applied across two parallel metal plates in a vacuum. An electron is released from rest at the negative plate as shown. The speed of the electron just before it reaches the positive plate is",
        question_image: "2025_Q10_Diagram.png",
        table_headers: "",
        option_a: "1.9x10⁻¹⁶ m/s",
        option_b: "6.5x10⁵ m/s",
        option_c: "2.1x10⁷ m/s",
        option_d: "4.2x10¹¹ m/s",
        option_e: "4.2x10¹⁴ m/s",
        correct_answer: "C"
    },
    {
        id: "2025-11",
        year: "2025",
        unit: "Electricity",
        topic: "Fields",
        question_text: "A proton enters a region of magnetic field as shown. The direction of the force exerted by the magnetic field on the proton as it enters the field is",
        question_image: "2025_Q11_Diagram.png",
        table_headers: "",
        option_a: "into the page",
        option_b: "out of the page",
        option_c: "towards the left of the page",
        option_d: "towards the bottom of the page",
        option_e: "towards the right of the page",
        correct_answer: "E"
    },
    {
        id: "2025-12",
        year: "2025",
        unit: "Particles",
        topic: "Nuclear",
        question_text: "The following statement represents a nuclear reaction. X represents",
        question_image: "2025_Q12_Formula.png",
        table_headers: "",
        option_a: "an alpha particle",
        option_b: "a beta particle",
        option_c: "a neutrino",
        option_d: "a neutron",
        option_e: "a proton",
        correct_answer: "A"
    },
    {
        id: "2025-13",
        year: "2025",
        unit: "Particles",
        topic: "Irradiance",
        question_text: "A small lamp is placed 0.40 m from a light meter in a darkened room. The irradiance of the light from the lamp is measured using the light meter. The irradiance at this distance is 20 mW/m². The light meter is now moved until the irradiance is 80 mW/m². The distance between the lamp and the light meter is now",
        question_image: "2025_Q13_Diagram.png",
        table_headers: "",
        option_a: "0.04 m",
        option_b: "0.10 m",
        option_c: "0.20 m",
        option_d: "0.80 m",
        option_e: "1.60 m",
        correct_answer: "C"
    },
    {
        id: "2025-14",
        year: "2025",
        unit: "Particles",
        topic: "Photoelectric",
        question_text: "A student sets up the following apparatus to investigate photoemission from a zinc plate. The reading on the ammeter can be increased by",
        question_image: "2025_Q14_Diagram.png",
        table_headers: "",
        option_a: "replacing the ultraviolet radiation with visible light",
        option_b: "replacing the ultraviolet radiation with infrared radiation",
        option_c: "decreasing the irradiance at the zinc plate",
        option_d: "reversing the connections to the battery",
        option_e: "allowing air into the glass tube",
        correct_answer: "D"
    },
    {
        id: "2025-15",
        year: "2025",
        unit: "Particles",
        topic: "Photoelectric",
        question_text: "Ultraviolet radiation of wavelength 250 nm is incident on a metal surface. The work function of the metal is 3.1 x 10⁻¹⁹ J. The energy of each photon of the ultraviolet radiation is",
        question_image: "",
        table_headers: "",
        option_a: "1.7 x 10⁻⁴⁰ J",
        option_b: "3.1 x 10⁻¹⁹ J",
        option_c: "4.9 x 10⁻¹⁹ J",
        option_d: "8.0 x 10⁻¹⁹ J",
        option_e: "1.1 x 10⁻¹⁸ J",
        correct_answer: "D"
    },
    {
        id: "2025-16",
        year: "2025",
        unit: "Waves",
        topic: "Interference",
        question_text: "A student sets up the apparatus shown to produce an interference pattern. S1 and S2 provide coherent sources of microwave radiation. A radiation detector is moved along the line from P to Q. The first minimum is detected at point X. The distance from S1 to X is 300 mm. The distance from S2 to X is 250 mm. The second minimum is detected at Y. The path difference S1Y - S2Y is",
        question_image: "2025_Q16_Diagram.png",
        table_headers: "",
        option_a: "25 mm",
        option_b: "75 mm",
        option_c: "100 mm",
        option_d: "150 mm",
        option_e: "250 mm",
        correct_answer: "D"
    },
    {
        id: "2025-17",
        year: "2025",
        unit: "Waves",
        topic: "Refraction",
        question_text: "A ray of monochromatic light passes through a glass block into air as shown. The critical angle for the glass block is 37.0° for this light. Angle X is",
        question_image: "2025_Q17_Diagram.png",
        table_headers: "",
        option_a: "22.8°",
        option_b: "27.5°",
        option_c: "30.7°",
        option_d: "62.5°",
        option_e: "67.2°",
        correct_answer: "B"
    },
    {
        id: "2025-18",
        year: "2025",
        unit: "Waves",
        topic: "Refraction",
        question_text: "A ray of monochromatic light in air has speed c, wavelength λ, and frequency f. The ray of light passes from air into a substance. The refractive index of the substance is 2.0 for this light. Which row in the table shows the speed, wavelength, and frequency of the light in the substance?",
        question_image: "",
        table_headers: "Speed | Wavelength | Frequency",
        option_a: "c | λ | f",
        option_b: "c | 2λ | 0.5f",
        option_c: "0.5c | 2λ | f",
        option_d: "0.5c | 0.5λ | 0.5f",
        option_e: "0.5c | 0.5λ | f",
        correct_answer: "E"
    },
    {
        id: "2025-19",
        year: "2025",
        unit: "Electricity",
        topic: "Circuits",
        question_text: "A circuit is set up as shown. The total resistance between X and Y is",
        question_image: "2025_Q19_Diagram.png",
        table_headers: "",
        option_a: "1.1 Ω",
        option_b: "1.7 Ω",
        option_c: "4.6 Ω",
        option_d: "5.6 Ω",
        option_e: "14 Ω",
        correct_answer: "D"
    },
    {
        id: "2025-20",
        year: "2025",
        unit: "Electricity",
        topic: "Circuits",
        question_text: "In the circuits shown below, the lamps are identical. The power supply has negligible internal resistance. In which circuit is the greatest power dissipated in the lamp?",
        question_image: "",
        table_headers: "",
        option_a: "[IMG]2025_Q20_A.png",
        option_b: "[IMG]2025_Q20_B.png",
        option_c: "[IMG]2025_Q20_C.png",
        option_d: "[IMG]2025_Q20_D.png",
        option_e: "[IMG]2025_Q20_E.png",
        correct_answer: "A"
    },
    {
        id: "2025-21",
        year: "2025",
        unit: "Electricity",
        topic: "Circuits",
        question_text: "A 7.0 Ω resistor is connected to a cell as shown. The internal resistance of the cell is 3.0 Ω. The switch is now closed. The reading on the ammeter is 0.15 A. Which row in the table shows the EMF of the cell and the reading on the voltmeter?",
        question_image: "2025_Q21_Diagram.png",
        table_headers: "EMF (V) | Reading on voltmeter (V)",
        option_a: "0.45 | 1.05",
        option_b: "1.05 | 0.45",
        option_c: "0.60 | 0.45",
        option_d: "1.50 | 1.05",
        option_e: "1.50 | 0.45",
        correct_answer: "D"
    },
    {
        id: "2025-22",
        year: "2025",
        unit: "Electricity",
        topic: "Circuits",
        question_text: "A battery has an EMF of 12 V and an internal resistance of 0.40 Ω. Two identical resistors each of resistance R are connected to the battery as shown. The reading on the ammeter is 4.0 A. The resistance R is",
        question_image: "2025_Q22_Diagram.png",
        table_headers: "",
        option_a: "0.77 Ω",
        option_b: "2.6 Ω",
        option_c: "3.0 Ω",
        option_d: "3.4 Ω",
        option_e: "5.2 Ω",
        correct_answer: "E"
    },
    {
        id: "2025-23",
        year: "2025",
        unit: "Particles",
        topic: "Semiconductors",
        question_text: "A student makes the following statements about red and blue LEDs.<br><br>I The gap between the valence band and the conduction band is larger for red LEDs than blue LEDs.<br>II Red LEDs emit photons of longer wavelength than blue LEDs.<br>III The potential difference across an LED determines the wavelength of the photons emitted.<br><br>Which of these statements is/are correct?",
        question_image: "",
        table_headers: "",
        option_a: "I only",
        option_b: "II only",
        option_c: "III only",
        option_d: "I and II only",
        option_e: "I, II and III",
        correct_answer: "B"
    },
    {
        id: "2025-24",
        year: "2025",
        unit: "Uncertainties",
        topic: "Stats",
        question_text: "A student measures the acceleration of a toy car down a slope. The experiment is repeated and the following values for the acceleration are recorded.<br><br>0.28 m/s² 0.29 m/s² 0.34 m/s² 0.30 m/s² 0.29 m/s²<br><br>Which row in the table shows the mean value of the acceleration and the approximate random uncertainty in the mean value of the acceleration?",
        question_image: "",
        table_headers: "Mean value of the acceleration (m/s²) | Approximate random uncertainty (m/s²)",
        option_a: "0.29 | 0.01",
        option_b: "0.29 | 0.06",
        option_c: "0.30 | 0.01",
        option_d: "0.30 | 0.06",
        option_e: "0.34 | 0.06",
        correct_answer: "C"
    },
    {
        id: "2025-25",
        year: "2025",
        unit: "Space",
        topic: "Gravitation",
        question_text: "A black hole can be formed from a star which has become so massive it collapses under its own gravitational force. The radius r of a black hole is calculated using the relationship shown.<br><br>Where:<br>G is the Universal Constant of Gravitation<br>M is the mass of the star<br>c is the speed of light<br><br>A star of mass 1.99 x 10³¹ kg collapses to form a black hole. The radius of this black hole is",
        question_image: "2025_Q25_Formula.png",
        table_headers: "",
        option_a: "7.37 x 10³ m",
        option_b: "1.47 x 10⁴ m",
        option_c: "2.95 x 10⁴ m",
        option_d: "8.85 x 10¹² m",
        option_e: "4.33 x 10¹⁵ m",
        correct_answer: "C"
    }
];